export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const SET_LOADING = "SET_LOADING";
export const GET_VIDEOGAME_DETAILS = "GET_VIDEOGAME_DETAILS";

